language: ruby
sudo: false

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.*
  - 2.2.*
  - 2.3.0
  - ruby-head

addons:
  apt_packages:
    - libgmp3-dev

branches:
  only:
    - master

script:
  - bundle exec rake test
  - bundle exec rubocop

